image: texlive/texlive:latest
stages:
  - build
build_pdf:
  stage: build
  resource_group: $CI_COMMIT_REF_SLUG
  tags:
    - spacehub
  script:
    - apt-get update && apt-get install -y python3-pip python3-venv poppler-utils
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt
    - python3 CHARTS.py
    - python3 GENERATOR.py
    - latexmk -pdf INTRO.tex
    - latexmk -pdf IMAGES.tex
    - python3 CONVERTER.py
  artifacts:
    paths:
      - INTRO.pdf
      - IMAGES.pdf
      - IMAGES.zip
      - WORKSHEET.zip
