name: Continuous
on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install
        run: |
          sudo apt-get install poppler-utils python3-pip
          python -m pip install -r requirements.txt
          python CHARTS.py
          python GENERATOR.py
      - name: Compile
        uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: |
            latexmk -pdf INTRO.tex
            latexmk -pdf IMAGES.tex
      - name: Convert
        run: |
          python CONVERTER.py
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in INTRO.pdf IMAGES.pdf IMAGES.zip WORKSHEET.zip; do
            gh release upload latest "$file" --clobber
          done
