name: Continuous
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install
        run: |
          sudo apt-get install poppler-utils python3-pip
          python -m pip install -r requirements.txt
          python CHARTS.py
          python GENERATOR.py
      - name: Compile
        uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: |
            latexmk -pdf INTRO.tex
            latexmk -pdf IMAGES.tex
      - name: Convert
        run: |
          python CONVERTER.py
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: INTRO.pdf
          asset_name: INTRO.pdf
          tag: latest
          overwrite: true
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: IMAGES.pdf
          asset_name: IMAGES.pdf
          tag: latest
          overwrite: true
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: IMAGES.zip
          asset_name: IMAGES.zip
          tag: latest
          overwrite: true
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: WORKSHEET.zip
          asset_name: WORKSHEET.zip
          tag: latest
          overwrite: true
