on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: |
          sudo apt-get install poppler-utils python3-pip
          python -m pip install pdf2image
          python GENERATOR.py
      - name: Compile
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            latexmk -pdf INTRO.tex
            latexmk -pdf IMAGES.tex
      - name: Convert
        run: |
          python CONVERTER.py
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: INTRO.pdf
          asset_name: INTRO.pdf
          tag: latest
          overwrite: true
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: IMAGES.pdf
          asset_name: IMAGES.pdf
          tag: latest
          overwrite: true
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: IMAGES.zip
          asset_name: IMAGES.zip
          tag: latest
          overwrite: true
